image: ubuntu:18.04
before_script:
- export DEBIAN_FRONTEND=noninteractive   # avoid tzdata interactive configuration
- apt-get -qq update
- apt-get install -y apt-utils git libgmp-dev libmpfr-dev libmpc-dev libppl-dev $PKGS
- $PYTHON -m pip install --upgrade pip
# NOTE: currently it seems not possible to build the sdist without manually installing
# dependencies. pyproject.toml is ignored by the call to 'setup.py sdist' below and the
# install_requires of setuptools is broken with Cython.
- $PYTHON -m pip install setuptools wheel Cython cysignals sphinx "gmpy2>=2.1.0b1"
- $PYTHON setup.py sdist
- $PYTHON -m pip -v install dist/pplpy-*.tar.gz

.template_script:
  script: &test_script
  # run tests
  - $PYTHON setup.py test
  # build documentation
  - make -w -C docs html

python2.7:
  stage: test
  variables:
    PYTHON: python
    PKGS: python-pip python-sphinx python-configparser
  script: *test_script

python3.6:
  stage: test
  variables:
    PYTHON: python3
    PKGS: python3-pip python3-sphinx
  script: *test_script

python3.7:
  stage: test
  variables:
    PYTHON: python3.7
    PKGS: python3.7 python3.7-dev python3-pip python3-sphinx
  script: *test_script

python3.8:
  stage: test
  variables:
    PYTHON: python3.8
    PKGS: python3.8 python3.8-dev python3-pip python3-sphinx
  script: *test_script

linux:
  image: python:3.8
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python -m pip install cibuildwheel==2.3.0
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/
