sudo: required
language: python
os: linux
dist: trusty

matrix:
  include:

  - python: 2.7
    compiler: gcc

  - python: 2.7
    compiler: clang
    env:
      CC=clang
      CXX=clang++
      LDSHARED='clang -shared'

  - python: 3.4
    compiler: gcc

  - python: 3.4
    compiler: clang
    env:
      CC=clang
      CXX=clang++
      LDSHARED='clang -shared'

  - python: 3.5
    compiler: gcc

  - python: 3.5
    compiler: clang
    env:
      CC=clang
      CXX=clang++
      LDSHARED='clang -shared'

  - python: 3.6
    compiler: gcc

  - python: 3.6
    compiler: clang
    env:
      CC=clang
      CXX=clang++
      LDSHARED='clang -shared'

install:
  - sudo apt-get -qq update
  - sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev libppl-dev
  - pip install Cython --verbose --disable-pip-version-check
  - pip install gmpy2==2.1.0a1 --verbose --disable-pip-version-check --no-binary ":all:"
  - pip install cysignals --verbose --disable-pip-version-check
  - pip install . --verbose --no-index

script:
  - cd tests
  - python rundoctest.py
  - python setup.py build_ext --inplace
  - python -c "import testpplpy"
  - python setup2.py build_ext --inplace
  - python -c "import testpplpy2"
