language: python
notifications:
  slack:
    on_success: never
    on_failure : never
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# non python dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libgmp-dev libppl-dev
# command to install dependencies
install: 
  - pip install Cython
  - pip install cysignals
  - pip install . --upgrade
# command to run tests
script:
  - cd tests
  - python rundoctest.py
  - python setup.py build_ext --inplace
  - python -c "import testpplpy"
