name: Build wheels

on: 
   push:
   workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macOS-latest] #, windows-2019]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.0

      - name: Build wheels
        env:
          CIBW_BEFORE_ALL_LINUX: >
            yum -y install gmp-devel mpfr-devel &&
            cd /tmp &&
            curl -O https://www.bugseng.com/products/ppl/download/ftp/releases/1.2/ppl-1.2.tar.xz &&
            tar xf ppl-1.2.tar.xz &&
            cd ppl-1.2 &&
            ./configure --enable-interfaces=c++ --enable-coefficients=mpz --disable-fpmath &&
            make install &&
            cd .. &&
            curl -O https://ftp.gnu.org/gnu/mpc/mpc-1.2.1.tar.gz &&
            tar xf mpc-1.2.1.tar.gz &&
            cd mpc-1.2.1 &&
            ./configure &&
            make install

        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
